# Generated by Django 5.0.1 on 2024-01-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_mst',
        ),
        migrations.CreateModel(
            name='Product_sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.IntegerField()),
                ('cprice', models.IntegerField()),
                ('cimage', models.FileField(upload_to='images/')),
                ('cname', models.CharField(max_length=200)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_manager.product_mst')),
            ],
        ),
    ]
